fix sql statements and init scripts

diff --git a/manifest/etc/cont-init.d/99-roundcube b/manifest/etc/cont-init.d/99-roundcube
--- a/manifest/etc/cont-init.d/99-roundcube
+++ b/manifest/etc/cont-init.d/99-roundcube
@@ -1,15 +1,31 @@
 #!/usr/bin/with-contenv bash
 
+# TODO:
+# This is not atomic and not clean but "works with some ignorable errors", reasons:
+# 1. There is a mix in all .sql files of CREATE TABLE foo and CREATE TABLE IF NOT EXISTS foo, so
+# that some init files will always return successfully
+# 2. With the behaviour from 1. we cannot really check if we have to update or not
+# 3. Without writing PHP we cannot make use of the mysql URI, but this would be crazy too
+# 4. Possible solution: Make all steps check for existing tables and atomic executions, produce correct
+# error output to user
+
 echo "Running MySQL database initializations and migrations."
 
 export PATH=/var/www/bin:$PATH
 
-# roundcube
-echo "Initializing MySQL for roundcube."
-initdb.sh --dir /var/www/SQL
+cd /var/www
 
-# plugins
-while read dir; do
-  echo "Initializing MySQL for ${dir}."
-  initdb.sh --dir $dir
-done < /var/www/.plugin_db_init
+while IFS=':' read -r package_name dir; do
+    echo "Init MySQL schema for plugin ${package_name} and with directory ${dir}."
+    if ! initdb.sh --dir=$dir --create 2>/dev/null; then
+        echo "Init db for ${package_name} failed, but probably not fatal because db exists."
+    else
+        echo "Init db for ${package_name} succeeded."
+    fi
+    echo "Updating MySQL schema for ${package_name} and with directory ${dir}."
+    if ! updatedb.sh --package=${package_name} --dir=$dir 2>/dev/null; then
+        echo "Update db for ${package_name} failed, but probably not fatal because db exists."
+    else
+        echo "Update db for ${package_name} succeeded."
+    fi
+done < .db_init
